{% set name = "oneagent-sdk" %}
{% set version = "1.5.0.20221221.150433" %}
{% set pystring = py|string %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oneagent-sdk-{{ version }}.zip
  sha256: fbaefe71d5efa0e552261daaf7a87b48c5cc32d64412302803eb45292ac7ef67

build:
  number: 1
  skip: true  # [not linux]

requirements:
  host:
    - python
    - pip
    - wheel
    - oneagent-sdk-for-c
  run:
    - python

test:
  imports:
    - oneagent
    - oneagent._impl
  commands:
    - pip check
    - test -f "${PREFIX}/lib/python{{ pystring[0] }}.{{ pystring[1] }}/site-packages/oneagent/_impl/native/libonesdk_shared.so"
  requires:
    - pip

about:
  home: https://github.com/Dynatrace/OneAgent-SDK-for-Python
  summary: Dynatrace OneAgent SDK for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
