{% set name = "oneagent-sdk" %}
{% set version = "1.5.1.20240104.95100" %}
{% set pystring = py|string %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oneagent-sdk-{{ version }}.zip
  sha256: 2325b173b0f68b14b796e976cb5d640c0f89f410fce318179004203bd59d1607

build:
  number: 1
  skip: true  # [not linux]

requirements:
  host:
    - python
    - pip
    - wheel
    - oneagent-sdk-for-c
  run:
    - python

test:
  imports:
    - oneagent
    - oneagent._impl
  commands:
    - pip check
    - test -f "${PREFIX}/lib/python{{ pystring[0] }}.{{ pystring[1] }}/site-packages/oneagent/_impl/native/libonesdk_shared.so"
  requires:
    - pip

about:
  home: https://github.com/Dynatrace/OneAgent-SDK-for-Python
  summary: Dynatrace OneAgent SDK for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
